<?php
$data = array (
  85 => 
  array (
    'cat_id' => '85',
    'cat_name' => 'T恤',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => '229',
    'level' => 0,
    'id' => '85',
    'name' => 'T恤',
  ),
  88 => 
  array (
    'cat_id' => '88',
    'cat_name' => 'WEB 设计',
    'measure_unit' => '',
    'parent_id' => '85',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '88',
    'name' => 'WEB 设计',
  ),
  87 => 
  array (
    'cat_id' => '87',
    'cat_name' => '摄影',
    'measure_unit' => '',
    'parent_id' => '85',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '87',
    'name' => '摄影',
  ),
  86 => 
  array (
    'cat_id' => '86',
    'cat_name' => '插画',
    'measure_unit' => '',
    'parent_id' => '85',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '86',
    'name' => '插画',
  ),
);
?>